export enum OtpTiming {
  VERIFY_PLAYER_EMAIL = 'VERIFY_PLAYER_EMAIL',
  FORGOT_PLAYER_PASSWORD = 'FORGOT_PLAYER_PASSWORD',
  FORGOT_PLAYER_WITHDRAWAL_PASSWORD = 'FORGOT_PLAYER_WITHDRAWAL_PASSWORD',
  VERIFY_PLAYER_MOBILE = 'VERIFY_PLAYER_MOBILE',
  VERIFY_PLAYER_BANK_ACCOUNT = 'VERIFY_PLAYER_BANK_ACCOUNT',
  FIRST_SET_PLAYER_WITHDRAWAL_PASSWORD = 'FIRST_SET_PLAYER_WITHDRAWAL_PASSWORD',
  CHANGE_AGENT_PHONE_NUMBER = 'CHANGE_AGENT_PHONE_NUMBER',
  CHANGE_AGENT_EMAIL = 'CHANGE_AGENT_EMAIL',
}
